In [52]:
"""
Notebook used to read a xlsx file containing sheets of 96 well plates from the TECAN
"""

# Import libraries
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from statannotations.Annotator import Annotator


# Apply theme
sns.set_theme(style="whitegrid")

# Import csv file
input_file = "./20221206 TQ MB ATP E3.xlsx"
df = pd.read_excel(input_file)

# Print dataframe
df

,Application: Tecan i-control,Unnamed: 1,Unnamed: 2,Unnamed: 3,"Tecan i-control , 1.10.4.0",Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Device: infinite 200Pro,NaN,NaN,NaN,Serial number: 1305001439,NaN,NaN,NaN,Serial number of connected stacker:,NaN,NaN,NaN,NaN
1,Firmware: V_3.37_07/12_Infinite (Jul 20 2012/1...,NaN,NaN,NaN,"MAI, V_3.37_07/12_Infinite (Jul 20 2012/13.56.47)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Date:,2022-06-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Time:,5:21:43 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,System,NaN,NaN,NaN,AAW31009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,User,NaN,NaN,NaN,AAW31009\PowerUser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Plate,NaN,NaN,NaN,ThermoFischer Scientific-Nunclon 96 Flat Botto...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Plate-ID (Stacker),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Label: Label1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Mode,NaN,NaN,NaN,Luminescence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Attenuation,NaN,NaN,NaN,NONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Integration Time,NaN,NaN,NaN,1000,ms,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Settle Time,NaN,NaN,NaN,0,ms,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Start Time:,6/12/2022 5:21:49 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,Temperature: 29.3 °C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,<>,1,2.0,3.0,4,5,6.0,7.0,8,9.0,10.0,11.0,12.0
22,A,8235909,7888737.0,7873366.0,7916967,7898550,7894120.0,7858774.0,7836151,7787476.0,7810626.0,7748966.0,7575770.0
23,B,7900337,7543911.0,7571875.0,7632024,7647420,7515572.0,7571003.0,7649444,7530452.0,7558354.0,7539074.0,7501598.0
24,C,7766170,7431571.0,7413537.0,7480260,7454423,7441543.0,7482103.0,7409371,7443763.0,7456296.0,7388670.0,7383743.0
25,D,7701275,7403879.0,7379023.0,7369680,7411517,7432733.0,7422489.0,7330905,7402622.0,7424074.0,7367383.0,7352032.0
26,E,7675530,7351044.0,7343768.0,7363213,7445206,7394895.0,7413436.0,7330222,7323058.0,7411946.0,7302982.0,7294823.0
27,F,7618507,7262444.0,7284080.0,7259666,7424373,7352165.0,7347621.0,7316301,7313288.0,7397553.0,7266624.0,7297491.0
28,G,7748532,7251330.0,7252061.0,7339487,7361806,7407610.0,7247319.0,7240855,7283454.0,7319046.0,7158594.0,7240581.0
29,H,7738287,7299089.0,7374580.0,7358937,7383812,7376326.0,7383830.0,7279664,7304493.0,7389372.0,7196777.0,7231618.0
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,End Time:,6/12/2022 5:23:46 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [177]:
# input: excel sheet as df
# output: single column A1-H12 as df

# Stacking Method
##############################################
# isolate 96 well plate data
# stack all
#isolate values from row 0-95 in column 2
def plate_2_df_column(df):
    df1=df.iloc[22:30,1:13]
    df2 = df1.stack().reset_index()
    df3=df2.iloc[0:96,2]
    return df3

In [195]:
# Iterate through sheets Method
##############################################
# import xlsx with all sheets
# itertate through all of sheets
# load sheet to df
# transform 96 well plate to single column
# add column to master df with sheet name as column name
# add Group column and annotate
# export master_df as csv file

input_file = './20221206 TQ MB ATP E3.xlsx'

xls = pd.ExcelFile(input_file)
sheet_list = xls.sheet_names
master_df = pd.DataFrame()

for i in range(len(sheet_list)):
    current_df = pd.read_excel(xls, sheet_list[i])
    df_to_add = plate_2_df_column(current_df)
    master_df.insert(loc=i, column=sheet_list[i], value=df_to_add,)

Group_list=[]
Groups=["Control1", "TQ 10uM", "TQ 2uM", "MB 800nM", "MB 100nM", "TQ&MB hi", "TQ&MB lo", "Control2"]
for i in range(8):
    for j in range(12):
        Group_list.append(Groups[i])
    
master_df.insert(len(sheet_list),column="Group",value=Group_list)
master_df.to_csv(f'{input_file} CONVERSION',index=False)